Update index.md
opendr-eu/opendr pull request #182
Opened 2021-12-15 11:59 UTC by ManosMpampis

fixing outdated links

2021-12-15 16:37 UTC, ad-daniel approved these changes
Since it doesn't serve a purpose any longer, we can delete it. Thank you.

2021-12-18 20:32 UTC, passalis approved these changes
Thank you for the careful check of the docs and corrections! Seems fine to me.

2021-12-21 08:56 UTC, ad-daniel requested changes
Very nice, thank you very much for this effort!
I only have 3 small details to change

2021-12-21 08:56 UTC, ad-daniel commented on docs/reference/engine-target.md
> +  Construct a new Keypoint* object based from *keypoint*.
```suggestion
  Construct a new *Keypoint* object based from *keypoint*.
```

2021-12-21 08:56 UTC, ad-daniel commented on docs/reference/engine-target.md
> +  Construct a new BoundingBox3DList* object based on the *bounding_boxes_3d*.
```suggestion
  Construct a new *BoundingBox3DList* object based on the *bounding_boxes_3d*.
```

2021-12-21 08:56 UTC, ad-daniel commented on docs/reference/index.md
> +    - `c API` Module
```suggestion
    - `C API` Module
```

2021-12-21 14:31 UTC, passalis commented
Thank you! I committed the suggested changes, since Manos will not be available today.

2021-12-21 14:33 UTC, ad-daniel approved these changes
Thank you!

2021-12-21 14:35 UTC, passalis approved these changes

2021-12-21 15:29 UTC, merged