Αdded documentation for mxnet detectors
opendr-eu/opendr pull request #185
Opened 2021-12-16 18:26 UTC by vivinousi

2021-12-16 18:53 UTC, passalis submitted a review, later dismissed
Seems fine to me. Thank you!

2021-12-17 07:28 UTC, ad-daniel requested changes

2021-12-17 07:34 UTC, ad-daniel approved these changes
Thank you!

2021-12-17 08:38 UTC, passalis approved these changes

2021-12-17 10:50 UTC, merged