Add ROS2 object detection, face detection and semantic segmentation nodes
opendr-eu/opendr pull request #273
Opened 2022-06-28 11:49 UTC by tsampazk

Nodes additions:
- Object Detection 2D - SSD
- Object Detection 2D - Centernet
- Object Detection 2D - Detr
- Object Detection 2D - YOLOv3
- Face Detection Retinaface
- Semantic Segmentation Bisenet
- Added entries in setup.py for nodes

Bridge additions:
- Added to and from ros bounding box list methods
- Added to and from ros boxes methods

Finalization:
- [ ] Object Detection 2D - SSD
- [ ] Object Detection 2D - Centernet
- [ ] Object Detection 2D - Detr
- [ ] Object Detection 2D - YOLOv3
- [ ] Face Detection Retinaface
- [ ] Semantic Segmentation Bisenet
- [ ] Bridge methods

2022-07-11 13:31 UTC, stefaniapedrazzi requested changes
Thank you!
This PR seems fine to me.

2022-07-11 13:31 UTC, stefaniapedrazzi commented on projects/opendr_ws_2/src/opendr_perception/package.xml
> +  <description>penDR ROS2 nodes for the perception package</description>
```suggestion
  <description>OpenDR ROS2 nodes for the perception package</description>
```

2022-07-11 13:43 UTC, tsampazk commented
Thanks for the quick review @stefaniapedrazzi, i'll go ahead and squash&merge as soon as the tests complete.

2022-07-11 13:45 UTC, merged

2022-07-13 10:14 UTC, tsampazk commented
Hey @jelledouwe, i noticed that you are working on a ROS2 DETR object detection 2D node. In this PR i have already added the object detection 2D DETR node. I am sorry for the miscommunication on my part. Maybe you could take a look at it [here.](https://github.com/opendr-eu/opendr/blob/ros2/projects/opendr_ws_2/src/opendr_perception/opendr_perception/object_detection_2d_detr_node.py) I have made the needed necessary changes for ROS2, as well as changes for internal consistency and consistency with other nodes.

Maybe you could modify that file straight away from a new branch out of ros2 branch if you feel that it needs changes?