Docker and installation improvements
opendr-eu/opendr pull request #276
Opened 2022-07-05 07:41 UTC by passalis

This PR improves docker images and installation process by
- Removing cache from docker images (about ~3GB size reduction)
- Reducing the number of intermediate layers created
- Adding missing ROS packages after building the main dependencies
- Adding a default argument (master) for branch creation

2022-07-11 13:18 UTC, stefaniapedrazzi reviewed
Thank you!

I just have two very minor suggestions to improve the text.

2022-07-11 13:18 UTC, stefaniapedrazzi commented on docs/reference/installation.md
> +If you need to use all the functionalities of the toolkit (e.g., ROS nodes, etc.), then you need either to use the pre-compiled docker images or to follow the installation instruction for cloning and
```suggestion
If you need to use all the functionalities of the toolkit (e.g., ROS nodes, etc.), then you need either to use the pre-compiled docker images or to follow the installation instructions for cloning and building the toolkit.
```

2022-07-11 13:18 UTC, stefaniapedrazzi commented on docs/reference/installation.md
> +Other platforms apart from Ubuntu 20.04, e.g., Windows, other linux distributions, etc., are currently supported through docker images.
```suggestion
Other platforms apart from Ubuntu 20.04, e.g., Windows, other Linux distributions, etc., are currently supported through docker images.
```

2022-07-13 07:23 UTC, ad-daniel requested changes
Thank you

2022-07-13 07:23 UTC, ad-daniel commented on docs/reference/installation.md
> +All the required dependecies will be automatically installed (or explicit instructions are provided).
```suggestion
All the required dependencies will be automatically installed (or explicit instructions are provided).
```

2022-07-13 08:20 UTC, ad-daniel approved these changes

2022-07-13 10:07 UTC, merged