Ros1 fixes heart anomaly detection
opendr-eu/opendr pull request #330
Opened 2022-10-10 07:11 UTC by minhquoc0712

Fixed:

- Update device code selection.
- Update argparse.
- Update input and output topic name, and docstring accordingly.

2022-10-11 08:13 UTC, tsampazk requested changes
Thank you for the updates in this node, changes look good and the node seems to run smoothly. I have left two very minor comments, and after those it will be good to go!

2022-10-11 08:13 UTC, tsampazk commented on projects/opendr_ws/src/perception/scripts/heart_anomaly_detection.py
>          :type prediction_topic: str
Mismatched docstring.

```suggestion
        :param output_heart_anomaly_topic: Topic to which we are publishing the predicted class
        :type output_heart_anomaly_topic: str
```

2022-10-11 08:13 UTC, tsampazk commented on projects/opendr_ws/src/perception/scripts/heart_anomaly_detection.py
>      # Select the device for running
This comment could be removed
```suggestion
```

2022-10-12 06:42 UTC, ad-daniel requested changes
Just a detail, thank you

2022-10-12 06:42 UTC, ad-daniel commented on projects/opendr_ws/src/perception/scripts/heart_anomaly_detection.py
> +    parser.add_argument("--model", type=str, default="anbof", help="model to be used for prediction: anbof or gru")
```suggestion
    parser.add_argument("--model", type=str, default="anbof", help="model to be used for prediction: anbof or gru",
                        choices=["anbof", "gru"])
```

2022-10-13 08:20 UTC, ad-daniel approved these changes
Thank you

2022-10-13 08:29 UTC, tsampazk approved these changes

2022-10-13 08:35 UTC, merged