Ros1 fixes speech command recognition
opendr-eu/opendr pull request #331
Opened 2022-10-10 07:24 UTC by minhquoc0712

Fixed:

- Update device code selection.
- Update argparse.
- Update input and output topic name, and docstring accordingly.

2022-10-11 08:53 UTC, tsampazk submitted a review, later dismissed
Thank you for the updates in this node. Looks good and runs smoothly!

2022-10-12 06:31 UTC, ad-daniel requested changes
Just a detail

2022-10-12 06:31 UTC, ad-daniel commented on projects/opendr_ws/src/perception/scripts/speech_command_recognition.py
> +                        help="Model to be used for prediction: matchboxnet or quad_selfonn")
```suggestion
                        help="Model to be used for prediction: matchboxnet, edgespeechnets or quad_selfonn")
```

2022-10-13 08:19 UTC, ad-daniel approved these changes

2022-10-13 08:28 UTC, tsampazk approved these changes

2022-10-13 08:31 UTC, merged