Ambiguity measure
opendr-eu/opendr pull request #361
Opened 2022-11-29 10:53 UTC by jelledouwe

This PR contains the AmbiguityMeasure tool for human robot interaction. It is related to one of our recent publications. We also created a [colab](https://colab.research.google.com/github/opendr-eu/opendr/blob/ambiguity_measure/projects/python/utils/ambiguity_measure/ambiguity_measure_tutorial.ipynb).

2022-12-07 13:22 UTC, ad-daniel requested changes
Thank you, being an utility I think what you did is sufficient. I have however a couple of comments:

- you have created a test (and locally it worked for me) but currently the tool is not being tested in the CI (you need to add it to the .yml files, both master and develop)
- I believe the the intent is for this tool to be distributed separately (like we do for the hyperparameter tuner), in which case you also need to add it to packages.txt so that one is created for it
- add a changelog entry

2022-12-07 13:22 UTC, ad-daniel commented on docs/reference/ambiguity_measure.md
> +- **threshold**: *float*\
```suggestion
- **threshold**: *float, default=0.5*\
```

2022-12-07 13:22 UTC, ad-daniel commented on docs/reference/ambiguity_measure.md
> +- **temperature**: *float*\
```suggestion
- **temperature**: *float, default=1.0*\
```

2022-12-07 13:22 UTC, ad-daniel commented on docs/reference/ambiguity_measure.md
> +  Temperature of the sigmoid function. Should be > 0.
```suggestion
  Temperature of the sigmoid function.
  Should be > 0.
```

2022-12-07 13:22 UTC, ad-daniel commented on docs/reference/ambiguity_measure.md
> +* **Ambiguity measure example.**
```suggestion
* **Ambiguity measure example**
```

2022-12-07 13:22 UTC, ad-daniel commented on docs/reference/ambiguity_measure.md
> +
```suggestion
```

2022-12-07 13:22 UTC, ad-daniel commented on src/opendr/utils/ambiguity_measure/__init__.py
> +
```suggestion
```

2022-12-08 10:35 UTC, jelledouwe commented
> Thank you, being an utility I think what you did is sufficient. I have however a couple of comments:
> 
>     * you have created a test (and locally it worked for me) but currently the tool is not being tested in the CI (you need to add it to the .yml files, both master and develop)
> 
>     * I believe the the intent is for this tool to be distributed separately (like we do for the hyperparameter tuner), in which case you also need to add it to packages.txt so that one is created for it
> 
>     * add a changelog entry

Hi Daniel, thanks for the review! I believe the test is currently already tested in the CI. At least, it appears in the actions on this branch under the util tests. I added the entry to the package list and the changelog.

2022-12-08 10:43 UTC, ad-daniel submitted a review, later dismissed
Yes you're right, it's being run in the `utils` job, I didn't see it. Thank you!

2022-12-08 10:54 UTC, tsampazk submitted a review, later dismissed
Changes look good to me, thank you!

2022-12-08 11:28 UTC, ad-daniel approved these changes

2022-12-08 11:34 UTC, tsampazk approved these changes

2022-12-08 12:41 UTC, merged