Single Demo Grasp update
opendr-eu/opendr pull request #366
Opened 2022-11-30 21:59 UTC by Zorrander

This PR splits the single demo grasp tool in two modules:

- In perception adds a detectron2 learner class and its corresponding ROS node for grasp pose detection 
- In control, ROS nodes to actuate a robot arm and an example using the perception to perform a pick and place task

2023-01-17 08:24 UTC, ad-daniel requested changes
Thank you! I'll test the demos once some of the issues are addressed/clarified

- Are the scripts under `opendr/src/opendr/control/single_demo_grasp` still relevant? Since you added a .rosinstall file they might clash. If not needed anymore they should be removed and the Makefiles adapted accordingly
- detectron2 learner class should be documented and added to the index.md file
- the documentation of the old learner (`single-demonstration-grasping.md`) is no longer necessary correct? If so it should be deleted and references to it remove from the index.md
- demo should be referenced in the index.md file
- I don't believe ros2 nodes are provided. This is intended? (I recall a discussion about some packages not existing yet for ros2)
- Missing changelog entry

2023-01-17 08:24 UTC, ad-daniel commented on projects/python/perception/object_detection_2d/detectron2/README.md
> +    TODO
As far as I can tell, the demos are available so this should be updated

2023-01-17 08:24 UTC, ad-daniel commented on projects/python/perception/object_detection_2d/detectron2/eval_demo.py
> +    temp = "/home/opendr/Gaurang/engineAssembly/Dataset/"
should be a parameter and default to a better location relative to the demo

2023-01-17 08:24 UTC, ad-daniel commented on projects/python/perception/object_detection_2d/detectron2/inference_demo.py
> +    temp = "/home/opendr/Gaurang/engineAssembly/Dataset/"
ditto

2023-01-17 08:24 UTC, ad-daniel commented on src/opendr/perception/object_detection_2d/__init__.py
> +from opendr.perception.object_detection_2d.detectron2.detectron2_learner import Detectron2Learner
wrong merge, yolov5 shouldn't be removed or it would break stuff

2023-01-17 08:24 UTC, ad-daniel commented on src/opendr/perception/object_detection_2d/__init__.py
> +           'transforms', 'draw_bounding_boxes', 'ClusterNMS', 'FastNMS', 'SoftNMS', 'Seq2SeqNMSLearner']
ditto, lost yolo here too

2023-01-17 08:24 UTC, ad-daniel commented on tests/sources/tools/perception/object_detection_2d/detectron2/test_detectron2.py
> +# Copyright 2020-2022 OpenDR European Project
```suggestion
# Copyright 2020-2023 OpenDR European Project
```

2023-01-31 13:44 UTC, Zorrander commented on projects/opendr_ws/src/control/src/control/gripper_controller.py
> +    def stop(self):
I removed it

2023-01-31 14:54 UTC, Zorrander commented on projects/opendr_ws/src/perception/README.md
> +# Perception Package
Yes it was. I moved the documentation to the new folder.

2023-01-31 15:37 UTC, Zorrander commented on projects/opendr_ws/src/control/scripts/arm_node.py
> +
No, removing it

2023-10-30 09:37 UTC, passalis commented
This PR is probably stale. We can re-open if needed.

2023-10-30 09:37 UTC, closed without merging