facial expression recognition demo update (FPS added)
opendr-eu/opendr pull request #405
Opened 2023-02-06 14:49 UTC by negarhdr

This PR adds FPS to the webcam demo of facial expression recognition.

2023-02-06 14:54 UTC, passalis submitted a review, later dismissed
Thank you!

2023-02-07 07:54 UTC, tsampazk requested changes
Thanks! Just a minor thing.

2023-02-08 15:36 UTC, negarhdr commented
> Thanks! Just a minor thing.

Thanks for checking.

2023-02-09 08:27 UTC, tsampazk submitted a review, later dismissed
Thank you :smile:

2023-02-10 11:19 UTC, tsampazk commented on projects/python/perception/facial_expression_recognition/image_based_facial_emotion_estimation/inference_demo.py
> +    model_path = "./esr_9"
This change needs to be reverted probably?

2023-02-14 15:10 UTC, ad-daniel approved these changes
Thank you!

2023-02-15 09:18 UTC, tsampazk reviewed
Applied some PEP8 fixes that failed the tests. Just noticed, is this indeed meant to merge into master?

2023-02-15 11:31 UTC, ad-daniel approved these changes
It's fine since it's a demo and doesn't impact functionality, thank you!

2023-02-15 11:35 UTC, tsampazk approved these changes

2023-02-15 12:52 UTC, merged