Object detection 2d camera demos
opendr-eu/opendr pull request #408
Opened 2023-02-13 17:04 UTC by ManosMpampis

This PR contains camera demos for OpenDR's object detection tools in python and C api.
Additionally included is a change to the Nanodet tool that makes it run almost 2 times faster than before.

2023-02-13 17:08 UTC, ManosMpampis commented
This PR is a continuation of the ([#383](https://github.com/opendr-eu/opendr/pull/383)) and ([#352](https://github.com/opendr-eu/opendr/pull/352))

2023-02-16 12:15 UTC, tsampazk requested changes
Thank you! Some very minor comments.

2023-02-16 12:15 UTC, tsampazk commented on docs/reference/c-object-detection-2d-nanodet-jit-h.md
> +This function draws the given detections (*vector*) onto the input image (*image*) and then if (*shows*) value is zero, the image will be displayed until a key is pressed.
```suggestion
This function draws the given detections (*vector*) onto the input image (*image*) and then if (*show*) value is zero, the image will be displayed until a key is pressed.
```

2023-02-16 12:15 UTC, tsampazk commented on docs/reference/object-detection-2d-nanodet.md
> +  Specifies the iou threshold for nms in inference.
```suggestion
  Specifies the IOU threshold for NMS in inference.
```

2023-02-16 12:15 UTC, tsampazk commented on docs/reference/object-detection-2d-nanodet.md
> +  Specifies the iou threshold for nms in inference.
```suggestion
  Specifies the IOU threshold for NMS in inference.
```

2023-02-21 08:18 UTC, tsampazk approved these changes
LGTM thank you

2023-02-21 09:57 UTC, ad-daniel approved these changes
I got several false positives (multiple detections) in some of them but I don't think the problem comes from this PR but from the underlying model, I think we can merge it. Thank you

2023-02-21 16:04 UTC, ad-daniel commented
The failed test is a network timeout, I think we can merge

2023-02-21 16:04 UTC, merged