FSeq2-NMS
opendr-eu/opendr pull request #442
Opened 2023-06-28 06:55 UTC by charsyme

Implementation of the FSeq2-NMS method (for person detection only) using SSD as detector.

2023-08-22 21:52 UTC, charsyme commented
This PR is ready for review.

2023-08-30 11:03 UTC, tsampazk requested changes
Thank you @charsyme  I have some comments, most are minor inconsistencies between the docs and code and some other details.

2023-08-30 11:03 UTC, tsampazk commented on src/opendr/perception/object_detection_2d/nms/fseq2_nms/algorithm/__pycache__/__init__.cpython-38.pyc
I think this file should be removed from the remote repo as they are [marked in .gitignore](https://github.com/opendr-eu/opendr/blob/b3d6ce670cdf63469fc5766630eb295d67b3d788/.gitignore#L19)

2023-08-30 11:03 UTC, tsampazk commented on src/opendr/perception/object_detection_2d/nms/fseq2_nms/algorithm/__pycache__/fseq2_model.cpython-38.pyc
I think this file should be removed from the remote repo as they are [marked in .gitignore](https://github.com/opendr-eu/opendr/blob/b3d6ce670cdf63469fc5766630eb295d67b3d788/.gitignore#L19)

2023-08-30 11:25 UTC, tsampazk commented
@charsyme Please double-check if the suggestions are valid and batch commit them through the github UI for conveniency.

2023-08-31 12:27 UTC, charsyme commented on src/opendr/perception/object_detection_2d/nms/fseq2_nms/algorithm/__pycache__/fseq2_model.cpython-38.pyc
Done

2023-09-01 06:49 UTC, charsyme commented on src/opendr/perception/object_detection_2d/nms/fseq2_nms/fseq2_nms_learner.py
I re-ordered them, and change some of them to private (except from init_model). I did also the same for seq2seq_nms_learner.py.

2023-09-01 06:53 UTC, charsyme commented
@tsampazk I think I dealt with all the suggestions/comments. Sorry for some extra separate commits.

2023-09-01 07:32 UTC, tsampazk approved these changes
Thanks @charsyme, looks good to me! :ok_hand:

2023-09-01 07:48 UTC, passalis approved these changes
Thank you!

2023-09-01 07:48 UTC, merged