Adding prompt when transcribe with Whisper
opendr-eu/opendr pull request #462
Opened 2023-09-13 06:34 UTC by minhquoc0712

2023-09-26 08:15 UTC, tsampazk commented
The tests on `speech_transcription/vosk` fail. It seems that the certificates of the url used to download vosk models have expired. I think it's [this one](https://alphacephei.com/vosk/models) which indeed gives out a warning of expired certificates when visiting from the browser. It seems they expired today:

```
Websites prove their identity via certificates, which are valid for a set time period. 
The certificate for alphacephei.com expired on 9/26/2023.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

Found a similar issue [here](https://github.com/alphacep/vosk-api/issues/1015#issuecomment-1166334920) from last year.

One quick fix would be to disable verification [here](https://github.com/opendr-eu/opendr/blob/f4ff8b1292ac9aa9e37354c726d8add2087f34a6/src/opendr/perception/speech_transcription/vosk/vosk_learner.py#L154) by adding the `verify=False` argument. However, it still fails down the line on [this one](https://github.com/opendr-eu/opendr/blob/f4ff8b1292ac9aa9e37354c726d8add2087f34a6/src/opendr/perception/speech_transcription/vosk/vosk_learner.py#L227-L232). Following a quick search, i couldn't find an easy way to disable verification on that one. @minhquoc0712 could you please take a look at potential fixes and maybe include them on this PR?

2023-10-01 20:21 UTC, minhquoc0712 commented
@tsampazk , I run the `test_voks.py`, and it doesn't have any errors. I run it from my room's WiFi. Can you try again? Perhaps, Vosk developers made some fixes?

2023-10-02 07:28 UTC, tsampazk requested changes
Thank you @minhquoc0712, i have added some minor comments.

2023-10-02 07:28 UTC, tsampazk commented on projects/opendr_ws/src/opendr_perception/README.md
> +    rosrun opendr_perception speech_transcription_node.py --backbone whisper --model_name tiny.en --inital_prompt "Felix" --verbose True
```suggestion
    rosrun opendr_perception speech_transcription_node.py --backbone whisper --model_name tiny.en --initial_prompt "Felix" --verbose True
```

2023-10-02 07:28 UTC, tsampazk commented on projects/opendr_ws/src/opendr_perception/README.md
> +   - `--initial_prompt INITIAL_PROMPT`: Prompt to provide some context or instruction for the transcription, only for Whisper,
```suggestion
   - `--initial_prompt INITIAL_PROMPT`: Prompt to provide some context or instruction for the transcription, only for Whisper
```

2023-10-02 07:28 UTC, tsampazk commented on projects/opendr_ws_2/src/opendr_perception/README.md
> +    ros2 run opendr_perception speech_transcription --backbone whisper --model_name tiny.en --inital_prompt "Felix" --verbose True
```suggestion
    ros2 run opendr_perception speech_transcription --backbone whisper --model_name tiny.en --initial_prompt "Felix" --verbose True
```

2023-10-02 07:28 UTC, tsampazk commented on projects/opendr_ws_2/src/opendr_perception/README.md
> +   - `--initial_prompt INITIAL_PROMPT`: Prompt to provide some context or instruction for the transcription, only for Whisper,
```suggestion
   - `--initial_prompt INITIAL_PROMPT`: Prompt to provide some context or instruction for the transcription, only for Whisper
```

2023-10-02 08:55 UTC, tsampazk approved these changes
Looks good to me, thank you @minhquoc0712!

2023-10-03 07:16 UTC, omichel approved these changes
That looks good to me as well.
Thank you.

2023-10-03 10:18 UTC, merged